version: '3.8'

services:
  app_blue:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app_blue
    ports:
      - "6969:8000"
    networks:
      - web
    
  app_green:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: app_green
    ports:
      - "6970:8000"
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - app_blue
      - app_green
    networks:
      - web

networks:
  web:
    driver: bridge
